### ISSUE TITLE
Simple Camera Dolly

### ISSUE THREAD

**Issue by ExplosiveEggshells** [niu-gdo/IGDO-Fall-2023-Project#39]
# Overview
Some of our game's rooms will not be able to be fully encapsulated within one screen space. Therefore, we'll have need for a moving camera behavior that will pan to keep the character and a subsection of the room in frame.

# Detail
This will involve creating a new script, `CameraDolly.cs`, which will move the GameObject it is attached to to the position of a `target` transform (The player position, in most circumstances).

For now, we will acquire the player GameObject by searching for it via a tag- using `GameObject.FindGameObjectByTag("player")`.

Then, in the `LateUpdate` method, set the attached game object's transform position equal to the target's position.

### Remarks:
- Verify that the Player GameObject's tag is set to "Player", or else your `FindGameObjectByTag` method call will fail to find anything.
- Be sure to validate the returned value from `FindGameObjectByTag`. If it returns null, log a warning and be sure to not try and run the code in `LateUpdate` (We cannot move towards a null target!).
- We use `LateUpdate` rather than `Update` or `FixedUpdate` because `LateUpdate` will occur after all other update ticks. This generally helps reduce the amount of jitter experienced in moving camera systems. [Read More](https://www.occasoftware.com/blog/late-update-in-unity#:~:text=LateUpdate%20is%20an%20event%20function,LateUpdate%20is%20called%20every%20frame.)

# Tasks
- [ ] Create a "CameraDolly" GameObject in the scene and make the main camera a child of it.
- [ ] Create a `CameraDolly.cs` script and attach it to the created GameObject above.
    - [ ] On Start, find the player Transform by their tag and store it as a member variable
    - [ ] In `LateUpdate`, if the stored player transform is _not null_, move the GameObject's position to the player transform position.
