### ISSUE TITLE
Trim PlayerInformation Class

### ISSUE THREAD

**Issue by ExplosiveEggshells** [niu-gdo/IGDO-Fall-2023-Project#40]
# Overview
With the finalization of the Game Design Document, we have a much more clear understanding of how our player's health systems should work.

With this new context, our current implementation of player health has some features which will not be utilized in our game, so they should be removed for the sake of clarity.

In the process, we'll also set up the remainder of the framework needed to build some easier tasks off of our health system.

# Tasks
- [ ] Remove the following functionality from `PlayerInformation.cs`
    - [ ] Anything related to shields
    - [ ] Damage Resistance
- [ ] Modify `IDamageable.cs`...
    - [ ] Remove `HealDamage` (Not all Damageable items need to be able to heal).
- [ ] Add `IMortal.cs`, representing things that have health and can "die".
    - [ ] Add Actions `OnHealthChanged`
    - [ ] Add Getter for `CurrentHealth` and `MaximumHealth` properties.
    - [ ] Add `Die()` Method.
- [ ]  Add `IMortal` to `PlayerInformation.cs` and make it conform to the interface changes above.

# Related Issues
- #16: Introduction of `PlayerInformation` and `IDamageable` scripts.
